# Generated by Django 2.0.5 on 2018-05-30 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_resetemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetemail',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='resetemail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default="2018-05-30 15:29:22.994893"),
            preserve_default=False,
        ),
    ]
