# Generated by Django 2.0.5 on 2018-06-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180530_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetEmail',
            new_name='ResetPassword',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
