# Generated by Django 2.0.5 on 2018-06-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180601_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
