# Generated by Django 2.0.6 on 2018-06-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploaderPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('uploader_access', 'Has access to the uploader'), ('uploader_admin', 'Has uploader admin access')),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('server_type', models.CharField(choices=[('FAST DL', 'FAST DL'), ('FAST DL PUBLIC', 'FAST DL PUBLIC'), ('SERVER', 'SERVER'), ('SERVER PUBLIC', 'SERVER PUBLIC')], max_length=20)),
                ('map_cycle_location', models.CharField(blank=True, max_length=64)),
                ('map_location', models.CharField(max_length=64)),
                ('home_location', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionInfo',
            fields=[
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='uploader.Server')),
                ('connection', models.CharField(choices=[('FTP', 'FTP'), ('FTPS', 'FTPS'), ('SFTP', 'SFTP')], max_length=10)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('host_address', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='fast_download_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.Server'),
        ),
    ]
