# Generated by Django 2.0.6 on 2018-06-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20180606_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='fast_download_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.Server'),
        ),
    ]
